language: c
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libunwind8
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_install:
- wget https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh
- echo '#!/bin/bash' | cat - dotnet-install.sh > dotnet-install.sh.patched && mv dotnet-install.sh.patched dotnet-install.sh
- chmod +x dotnet-install.sh
- sudo ./dotnet-install.sh --channel preview --version 2.0.0-preview1-005783 -i /opt/dotnet
- sudo ln -s /opt/dotnet/dotnet /usr/bin/dotnet
script:
- pushd samples/KestrelSample && dotnet restore && dotnet build && popd
- pushd test/Tmds.Kestrel.Linux.Test && dotnet restore && dotnet test && popd
- dotnet pack src/Tmds.Kestrel.Linux --configuration Release --version-suffix "$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER"
  --output .
after_success:
- 'if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  curl -H "X-NuGet-ApiKey: $NUGET_APIKEY" -T Tmds.Kestrel.Linux.*-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.nupkg
  https://www.myget.org/F/tmds/api/v2/package ; fi'

env:
  global:
    secure: n9MHrC/DKw6MrTOBPWnvCbu5JxUGocci1LBTPXV4FNAn5JMh7CEEWCX1Nml/x7qfJVoe9tz+aD55IxKY//eTMUQet9Npimc7XXr6Dcjlqc9flE4zXd8WC2d3ch3VU1C+Dxv9nN1pT7n6oWgN8eOk4LALnFmjSsS+jiUruRn+GI7qUnbaHFx11Seoh6lN9qAhsLb57/U+e5HjYqAQyXwiMBdbLkcHPP/DYOLxoD//4WtYpNagzg82ba/CwqB03cAyvyTxjdfedLjbz6sgFXfkf3cr0d1qvav0ZYnyUn7gZ25cvRHFdMUDW9MD0EbF5UUFkyVGy7ugHu8vzScH7zirEBHbR4QIK0Y4sXH6O731fCRG9UzsBLMdTEtlvjljx/8N/vDnMBhWFdHy+yFqqNoR677hWho+zo+oY4oQ0gDab5hN2TKZRM2VT5OhHDUB0Vei30ukxpvGq7P958fDlTO8qq8NqjghWm0us0DqOz8u+P8A6RWW5YBgfQ3BpUX6KfVzeM8j2j9s5AuCiqJ09BfHiqswzqChQuE4wDEfhk2GXdfiHklqr+4tRIBhwXwDmXIPPJcylzc8fGBGXKYZMBEC4oeKK9OGMT5TNv9qBByUTRgW11v6YGH8DDZWn6UqiXeOTE49LqIqaeIk4zUmkQ5FdECc5p4SEkV6VCBQ+rBevkM=
